apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: banking

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-node
      containers:
        - name: frontend
          image: maniprem28/java-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

          